### ISSUE TITLE
Identical messages are causing warning: Duplicate keys detected: 'vlad mck: eee'. This may cause an update error.

### ISSUE THREAD

**Issue by vlamic** [Marmt-Group/app-vue-chat-widget#44]
If I add 2 absolutely identical messages in the messageList, I get a warning saying: Duplicate keys detected: 'vlad mck: eee'. This may cause an update error.

See screenshot.

![Screenshot 2021-10-05 at 16 20 36](https://user-images.githubusercontent.com/1814198/136041762-330ed48f-ecde-434a-8938-f1b5eb88f9a4.png)

**Comment by david-j-davis** [comment]
I see, you're welcome to submit a PR to fix what looks to be a simple
issue. Otherwise I'll have to put it on the list of things to do.

Thanks,
David

**Comment by vlamic** [comment]
@david-j-davis absolutely. here it is: https://github.com/Marmt-Group/app-vue-chat-widget/pull/45

**Comment by david-j-davis** [comment]
Thanks! Approved and merged.

**Comment by vlamic** [comment]
Thanks @david-j-davis. Could you publish the updated npm package?

**Comment by david-j-davis** [comment]
Hello, it should be published now at v0.3.3
